[package]
name = "achievements-recorder"
version = "1.0.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
windows = { version = "0.62.2", features = [
  "Foundation",
  "Media_Editing",
  "Media_Transcoding",
  "Storage",
  "Storage_Streams",
  "Win32_Foundation",
  "Win32_Graphics_Direct3D",
  "Win32_Graphics_Direct3D_Fxc",
  "Win32_Graphics_Direct3D11",
  "Win32_Graphics_Dxgi",
  "Win32_Graphics_Dxgi_Common",
  "Win32_Media_Audio",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Variant",
  "Win32_System_WinRT",
  "Win32_System_WinRT_Direct3D11",
] }
windows-capture = "2.0.1"

[patch.crates-io]
windows-capture = { path = "../vendor/windows-capture" }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = "s"
panic = "abort"
strip = "symbols"
